---
name: Release
on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_PAT }}
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-eslint
          branches: |
            ['main']
